### ISSUE TITLE
Supported display types

### ISSUE THREAD

**Issue by pavelru** [kbr-net/sdrive-max#24] opened 2019-10-18 19:20 UTC
Hello, I bought a display on the e-shop website https://arduino-shop.cz/arduino/1568-shield-lcd-tft-2-4-display-for-arduino-uno.html unfortunately not supported by you . I found that the following demo works on the recommendation of the e-shop https://arduino-shop.cz/docs/products/0/141/test_example_1487762760.zip. Could you include support for this type of display? Thank you very much for your time.

**Comment by pavelru** [comment] 2019-10-19 08:25
Just add that the display correctly displays the screen after writing the firmware atmega328-ili9329 but after performing the display calibration, the touch control stops working.
After writing the firmware version of atmega328-ili9340, the screen is upside down and mirrored.
And after writing the firmware version of atmega328-ili9341eeprom_writer.hex, the screen is mirrored, and after writing sdrive.hex the display cannot be calibrated. The touch control does not work.
![20191019_101104](https://user-images.githubusercontent.com/11569970/67140432-93abd080-f25a-11e9-840f-6ee931a820e5.jpg)
![20191019_101212](https://user-images.githubusercontent.com/11569970/67140434-9a3a4800-f25a-11e9-8a4a-4f01827ce2bd.jpg)
![20191019_100340](https://user-images.githubusercontent.com/11569970/67140444-a7efcd80-f25a-11e9-921b-9b028f464f6c.jpg)
![20191019_100607](https://user-images.githubusercontent.com/11569970/67140448-ad4d1800-f25a-11e9-8659-7bff19b0b623.jpg)
![20191019_100659](https://user-images.githubusercontent.com/11569970/67140450-b211cc00-f25a-11e9-9ab4-ab12f4868c0c.jpg)

**Comment by pavelru** [comment] 2019-10-19 11:33
I will add one more clarification. I recorded the progress of writing sdrive.hex on my mobile phone and after downloading any version I will briefly flash TFT ID: 9340 ... Then I do not understand why my version of firmware atmega328-ili9340 does not work correctly :(

**Comment by kbr-net** [comment] 2019-10-19 15:54
Please read https://github.com/kbr-net/sdrive-max/issues/18 and try the firmware v1.2b2 there.

**Comment by pavelru** [comment] 2019-10-19 16:12
Good morning and thank you for your answer. I tried to write this version of atmega328-ili9340i firmware as well. The display is shown in the attached photos.
![20191019_180436](https://user-images.githubusercontent.com/11569970/67148126-f96c7c80-f29b-11e9-8c34-c862276bdea2.jpg)
![20191019_180547](https://user-images.githubusercontent.com/11569970/67148131-025d4e00-f29c-11e9-8a79-a7baa2681c99.jpg)

**Comment by pavelru** [comment] 2019-10-19 16:30
I also run pin diagnostics see below if it helps.

Making all control and bus pins INPUT_PULLUP
Typical 30k Analog pullup with corresponding pin
would read low when digital is written LOW
e.g. reads ~25 for 300R X direction
e.g. reads ~30 for 500R Y direction

Testing : (A1, D7) = 32
Testing : (A2, D6) = 25
Diagnosing as:-
YP,YM:  (A1, D7) = 32
XM,XP:  (A2, D6) = 25

**Comment by kbr-net** [comment] 2019-10-19 20:56
Weird, this are the correct pins for ILI9329 and ILI9340. Calibration works, and then it hangs?
Then the problem is not the touchscreen, i think.
What happens when the Atari is powered on?

**Comment by pavelru** [comment] 2019-10-20 09:40
Hello, I enclose photos of the display and cable connection to the connector and to Arduino. The SD card is formatted by fat or fat32, and the sdrive.atr file is in the card's root. Unfortunately, nothing happens when you turn on Atari. Just growls and BASIC starts. Calibration is counterclockwise as shown in other photos.
![20191020_104339](https://user-images.githubusercontent.com/11569970/67157511-87dd0e80-f32d-11e9-8c15-0bbc4d80e225.jpg)
![20191020_112512](https://user-images.githubusercontent.com/11569970/67157514-90354980-f32d-11e9-9210-7df63724d188.jpg)
![20191020_104005](https://user-images.githubusercontent.com/11569970/67157519-9a574800-f32d-11e9-8b9e-a5c023a116c3.jpg)
![20191020_104016](https://user-images.githubusercontent.com/11569970/67157521-9deacf00-f32d-11e9-977c-2c44f32b4ca9.jpg)
![20191020_104025](https://user-images.githubusercontent.com/11569970/67157522-a0e5bf80-f32d-11e9-8ef7-e94043387aba.jpg)
![20191020_104037](https://user-images.githubusercontent.com/11569970/67157524-a4794680-f32d-11e9-822f-2776873d0b03.jpg)
![20191020_104053](https://user-images.githubusercontent.com/11569970/67157525-a80ccd80-f32d-11e9-9d4b-d46b6b4c8040.jpg)
![20191020_104104](https://user-images.githubusercontent.com/11569970/67157528-b0650880-f32d-11e9-9117-208ac04a08e4.jpg)
![20191020_110232](https://user-images.githubusercontent.com/11569970/67157533-b6f38000-f32d-11e9-90af-1faca95bb4f4.jpg)
![20191020_111024](https://user-images.githubusercontent.com/11569970/67157540-beb32480-f32d-11e9-9ccf-75293b86c436.jpg)

**Comment by kbr-net** [comment] 2019-10-20 11:03
Try with ILI9329 firmware, this looks the best, and also try to start Atari after calibration without display attached.

**Comment by kbr-net** [comment] 2019-10-20 11:11
There is also no response on touch if SD-Card is out and SIO not plugged in?

**Comment by pavelru** [comment] 2019-10-20 12:14
I installed the sdrive-max-v11\atmega328-ili9329 firmware and performed the steps you recommended. Even then, nothing happened. So I tried to use another SD card and sdrive.atr is loaded while Option is pressed. For some reason I don't want to work with a small 128MB SD card. Unfortunately, the touch control still does not work. But when I leave sdrive for some time and the screensaver comes up, so by touching the screen wakes up ...
![20191020_140355](https://user-images.githubusercontent.com/11569970/67159376-f5943500-f343-11e9-8d57-ca2c3a696469.jpg)

**Comment by kbr-net** [comment] 2019-10-20 15:43
Can you send me the first 2MB raw data of the SD-Card?
On Linux you can do this with: dd if=/dev/sdc of=sd.out bs=1M count=2; gzip sd.out
(where /dev/sdc is your card device)

**Comment by pavelru** [comment] 2019-10-20 15:53
I would send but unfortunately I do not use linux :( Is there any possibility to do this on win10?

**Comment by kbr-net** [comment] 2019-10-20 16:11
Maybe there are tools for win10, but i don't know about, sorry. Use a KNOPPIX CD?

I have also released a new beta v1.2b3 right now, please try: https://github.com/kbr-net/sdrive-max/releases/download/v1.2b3/sdrive-max-v12b3.zip

**Comment by pavelru** [comment] 2019-10-20 17:38
Unfortunately, the new firmware is mirrored. the touch control works very strangely.
![20191020_192914](https://user-images.githubusercontent.com/11569970/67163580-f42d3180-f370-11e9-8d8d-83e4b7eeca57.jpg)
![20191020_193110](https://user-images.githubusercontent.com/11569970/67163583-f8f1e580-f370-11e9-8db2-9ea995cb52a8.jpg)
![20191020_193506](https://user-images.githubusercontent.com/11569970/67163586-fd1e0300-f370-11e9-8596-890a0ae06951.jpg)

Tomorrow I will try to prepare an old NB with Linux and try to send the required files

**Comment by kbr-net** [comment] 2019-10-20 17:59
I'm a little bit confused now, in you second post the ILI9329 looks correct, which firmware is now with the correct display?

**Comment by pavelru** [comment] 2019-10-20 18:03
The last firmware I installed was beta sdrive-max-v12b3.zip

**Comment by kbr-net** [comment] 2019-10-20 18:29
Sorry, my fault, please try the same file again.

**Comment by pavelru** [comment] 2019-10-20 19:15
Nothing happens. I tried the latest firmware. Displays correctly and touch control works but as if for a large display. If I touch the middle of the screen at some point, I get to the file selection. But ... I sometimes get to the READY screen at the same place.

**Comment by kbr-net** [comment] 2019-10-20 19:47
Can you post a picture with the values in the middle at the end of calibration again?
You can initiate a recalibration by holding touch while power on.

**Comment by pavelru** [comment] 2019-10-21 07:08
Good morning, I'm sending the photo.
![20191021_090200](https://user-images.githubusercontent.com/11569970/67183649-4b1f1f00-f3e2-11e9-8e3c-0ff4bdfcd84a.jpg)

**Comment by kbr-net** [comment] 2019-10-21 15:53
Try to clear the bootblock of the problematic SD-Card, create a new partition table, and format it new.

The values of the calibration looks good, don't know, why it's not working...
Have made a firmware with touchpoint debug X, Y output in pixels. Left upper corner should be near 0, 0, right bottum 240, 320. Hope that helps!
[sdrive-max-v12b3-debug.zip](https://github.com/kbr-net/sdrive-max/files/3751780/sdrive-max-v12b3-debug.zip)

**Comment by pavelru** [comment] 2019-10-21 16:28
Good evening, thank you very much for your help. I send a photo and the next one is photographed the problem, why it does not work as it should. If I press the joint a little with my finger, the touch control works. I will have to claim the display from the seller. Once again, thank you very much for your continued help. If you can send a contribution, please write.
![20191021_180705](https://user-images.githubusercontent.com/11569970/67223947-81838b00-f430-11e9-92f9-307b4213991e.jpg)
![2019-10-21-18-13-44-634](https://user-images.githubusercontent.com/11569970/67223959-86483f00-f430-11e9-899f-853728d902ae.jpg)

**Comment by kbr-net** [comment] 2019-10-21 18:51
All right, but the firmware for ILI9329i is now the correct one?

**Comment by pavelru** [comment] 2019-10-22 10:16
Yes, touch control worked as far as possible. I will probably confirm tomorrow when I receive a new display.

**Comment by pavelru** [comment] 2019-10-23 14:49
Hello. Today I received a new display. After connecting to arduin, start up and recalibrate works at first good. I tried to upload a version of sdrive-max-v11\atmega328-ili9329, but it does not work after calibration touch control. I returned to the version of atmega328-ili9329i attaching the picture. Thank you very much again for your time.
![20191023_161917](https://user-images.githubusercontent.com/11569970/67404308-7ad15100-f5b3-11e9-9c6d-1190d57acdb1.jpg)

Now, after attaching the disk image and pressing Option + Reset, it displays this message as shown. He tried 2 SD cards and it is the same for both.
![20191023_164422](https://user-images.githubusercontent.com/11569970/67405493-2038f480-f5b5-11e9-8cf8-11725cf9c264.jpg)

**Comment by kbr-net** [comment] 2019-10-23 15:39
As far as i can see, you have connected the SIO power pin 10 to 5V, and also connected USB, this is no good idea, use only one power source!
And then try power on by holding OPTION, RESET does not always work correctly.

**Comment by pavelru** [comment] 2019-10-23 15:54
The first photo is sdrive connected to the PC and the second to the atari without additional usb power. The cable shown in the second photo charges my tablet.

**Comment by kbr-net** [comment] 2019-10-23 16:01
But sdrive.atr is loading the control program?

**Comment by pavelru** [comment] 2019-10-23 16:31
Sdrive.atr will load correctly. I select a disk image in D1 and the message appears after pressing Opt + Reset.

**Comment by kbr-net** [comment] 2019-10-23 16:39
Strange, "CMD Timeout" says, the CMD-Line is pulled low, but no command is sent to the SDM.

**Comment by kbr-net** [comment] 2019-10-23 16:42
Can you see the directory of the disk image in the control program by pressing "V"?

**Comment by pavelru** [comment] 2019-10-23 16:53
In the control program, after pressing L and I, I see a long file name and information and file. After the V label, the screen is blank, but the load indicator glows green. Press V to return to the control program.

**Comment by pavelru** [comment] 2019-10-23 17:01
This will appear when sdrive.atr is loaded.
![20191023_185910](https://user-images.githubusercontent.com/11569970/67416674-8464b400-f5c7-11e9-96e4-929a8f32bb73.jpg)

**Comment by kbr-net** [comment] 2019-10-23 18:11
> In the control program, after pressing L and I, I see a long file name and file information. After the V label, the screen is blank, but the load indicator glows green. Press V to return to the control program.

Show me this output please, if you have selected the image, which won't boot.

**Comment by pavelru** [comment] 2019-10-24 08:24
Hello, I'm sending a link to the video where you can see how it behaved. When I am newly downloaded BiboDos7 already works properly. The error was probably caused by copying to the SD card and disconnecting it incorrectly from the system.
https://photos.app.goo.gl/g5AVPu3a7DT9qSzL9

**Comment by kbr-net** [comment] 2019-10-24 21:15
Thank you, then we can close this issue, i think.

**Closed by kbr-net** 2019-10-24 21:15 UTC
